apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: {{ template "project.name" . }}
    chart: {{ template "project.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: apache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "project.name" . }}
        role: apache
    spec:
      containers:
        - name: nextcloud
          image: "nextcloud:{{ .Values.build_id }}"
          volumeMounts:
            - name: config-volume
              mountPath: /mnt
          env:
            - name: TIER
              value: "{{ .Values.tier }}"
            - name: GIT_BRANCH
              value: "{{ .Values.git_branch }}"
            - name: ROLE
              value: "agent"
            - name: BUILD_ID
              value: "{{ .Values.build_id }}"
            - name: BOOTSTRAP_SERVERS
              value: "{{ .Values.kafka.bootstrap_servers | join "," }}"
            - name: SCHEMA_REGISTRY_URL
              value: "{{ .Values.kafka.schema_registry_url }}"
            - name: LOGSTASH
              value: "{{ .Values.logstash.host }}:{{ .Values.logstash.port }}"
          resources:
            requests:
              memory: "1000Mi"
              cpu: "1000m"
            limits:
              memory: "2000Mi"
              cpu: "4000m"
      volumes:
        - name: config-volume
          configMap:
            name: config
      imagePullSecrets:
        - name: regcred
