kind: PersistentVolume
apiVersion: v1
metadata:
  name: nextcloud
  labels:
    app: {{ template "project.name" . }}
    chart: {{ template "project.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: nextcloud-hostpath
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/nextcloud"
  capacity:
    storage: 100Mi