apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
  labels:
    app: {{ template "project.name" . }}
    chart: {{ template "project.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.nextcloud.pass | b64enc | quote }}
