apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextcloud
  labels:
    app: {{ template "project.name" . }}
    chart: {{ template "project.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ .Values.nextcloud.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: nextcloud
              servicePort: 80
