kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-config
  labels:
    app: {{ template "project.name" . }}
    chart: {{ template "project.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi